apiVersion: v1
kind: Secret
metadata:
  name: shortener-secrets
  namespace: url-shortener
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # base64: postgres
  POSTGRES_PASSWORD: eW91cl9zZWN1cmVfcGFzc3dvcmQ= # base64: your_secure_password
  RABBITMQ_USER: Z3Vlc3Q= # base64: guest
  RABBITMQ_PASSWORD: Z3Vlc3Q= # base64: guest
  JWT_KEY: eW91ci1zZWN1cmUtam10LWtleS1oZXJlLTMyY2hhcnM= # base64: your-secure-jwt-key-here-32chars