apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: url-shortener
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: url-shortener-user-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__Postgres
          value: Host=postgres-service;Database=shortener;Username=$(POSTGRES_USER);Password=$(POSTGRES_PASSWORD)
        - name: ConnectionStrings__Redis
          value: redis-service:6379
        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: shortener-secrets
              key: JWT_KEY
        - name: Jwt__Issuer
          value: UrlShortener
        - name: Jwt__Audience
          value: UrlShortener
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: user-service
              topologyKey: kubernetes.io/hostname