FROM mcr.microsoft.com/devcontainers/dotnet:1-8.0

# Set working directory
WORKDIR /workspace

# Copy all files from the current directory to the container
COPY . .

# Set default command
CMD ["/bin/bash"]
